const $=id=>document.getElementById(id);
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let queue=LANDMARKS.map((_,i)=>i),pos=0,score=0,answered=false,hinted=false,review=false,seen=new Set(),missed=new Set(),correct=new Set(),view=null,Point=null,fallback=false,moveId=0;
const current=()=>LANDMARKS[queue[pos]];
function render(){answered=false;hinted=false;$('play').hidden=false;$('finish').hidden=true;const l=current();$('clue').textContent=l.c;$('roundlabel').textContent=`${review?'REVIEW':'EXPEDITION'} ${String(pos+1).padStart(2,'0')} / ${queue.length}`;$('progress').style.width=`${pos/queue.length*100}%`;$('location').textContent=`MYSTERY LOCATION ${String(pos+1).padStart(2,'0')}`;$('feedback').hidden=true;$('next').hidden=true;$('hint').hidden=false;$('hinttext').hidden=true;$('hint').disabled=false;$('options').replaceChildren();const pool=LANDMARKS.map((d,i)=>i).filter(i=>i!==queue[pos]&&LANDMARKS[i].t===l.t);shuffle([queue[pos],...shuffle(pool).slice(0,3)]).forEach((id,i)=>{const b=document.createElement('button');b.dataset.id=id;const key=document.createElement('em');key.textContent=String.fromCharCode(65+i);const label=document.createElement('span');label.textContent=LANDMARKS[id].n;b.append(key,label);b.onclick=()=>answer(id);$('options').append(b)});fly();if(window.PHOTOS)showPhoto();}
function answer(id){if(answered)return;answered=true;const idx=queue[pos],l=current(),ok=id===idx,points=ok?(hinted?75:100):0;score+=points;seen.add(idx);if(ok){correct.add(idx);missed.delete(idx)}else{missed.add(idx)}$('score').textContent=score;$('count').textContent=seen.size;$('progress').style.width=`${(pos+1)/queue.length*100}%`;for(const b of $('options').children){b.disabled=true;if(+b.dataset.id===idx)b.classList.add('correct');else if(+b.dataset.id===id)b.classList.add('wrong')}$('hint').hidden=true;$('feedback').hidden=false;$('feedback').innerHTML=`<span class="result-tag">${ok?'LOCATION IDENTIFIED · +'+points+' XP':'NEW LANDMARK DISCOVERED'}</span><h2>${l.n}</h2><p>${l.p} · ${l.t}</p><p>${l.f}</p><a href="${l.s}" target="_blank" rel="noopener noreferrer">Read the source ↗</a>`;$('next').hidden=false;$('next').textContent=pos===queue.length-1?'See expedition results →':'Next destination →';$('location').textContent=l.n.toUpperCase();}
$('hint').onclick=()=>{if(answered||hinted)return;hinted=true;$('hinttext').hidden=false;$('hinttext').textContent=current().p;$('hint').disabled=true;};
$('next').onclick=()=>{if(!answered)return;if(++pos<queue.length)render();else finish()};
function finish(){$('play').hidden=true;$('finish').hidden=false;$('roundlabel').textContent='EXPEDITION COMPLETE';$('progress').style.width='100%';$('finish').innerHTML=`<span class="eyebrow">${missed.size?'KEEP EXPLORING':'ALL LANDMARKS IDENTIFIED'}</span><h1>Your continent.<br>Discovered.</h1><div class="big-score">${score}<small style="font-size:20px;letter-spacing:0"> XP</small></div><p>You’ve visited ${seen.size} of ${LANDMARKS.length} landmarks and correctly identified ${correct.size}.</p><p>${missed.size?`${missed.size} landmark${missed.size===1?' needs':'s need'} another look. Revisit them to strengthen your recognition.`:'Great work. Try a shuffled expedition to put your recognition to the test.'}</p>${missed.size?'<button id="review" class="primary">Revisit missed landmarks →</button>':''}<button id="again" class="primary">Play a shuffled expedition</button><button id="openbook" style="width:100%;margin-top:12px">Open field guide</button>`;if($('review'))$('review').onclick=()=>{queue=shuffle([...missed]);pos=0;review=true;render()};$('again').onclick=()=>{queue=shuffle(LANDMARKS.map((_,i)=>i));pos=0;score=0;review=false;seen.clear();correct.clear();missed.clear();$('score').textContent=0;$('count').textContent=0;render()};$('openbook').onclick=openGuide;}
function openGuide(){$('catalog').replaceChildren();LANDMARKS.forEach((l,i)=>{const d=document.createElement('article');if(seen.has(i)){d.className='entry';d.innerHTML=`<small>${l.t} · ${correct.has(i)?'Identified':'Revisit'}</small><h3>${l.n}</h3><p>${l.p}</p><p>${l.f}</p><a href="${l.s}" target="_blank" rel="noopener noreferrer">Original source ↗</a>`}else{d.className='locked';d.textContent=`${String(i+1).padStart(2,'0')} · Undiscovered landmark`}$('catalog').append(d)});$('dialog').showModal()}
$('guide').onclick=openGuide;$('close').onclick=()=>$('dialog').close();$('dialog').addEventListener('click',e=>{if(e.target===$('dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
function mapFallback(){fallback=true;$('status').textContent='3D unavailable. Use the aerial view and clue to continue.';$('aerial').hidden=false;$('aerial').onerror=()=>{$('aerial').hidden=true;$('status').textContent='Map imagery is unavailable. You can still play using the landmark photo and clue.'};$('orbit').disabled=true;$('top').disabled=true;showAerial();}
function showAerial(){const l=current();if(!l)return;const dy=l.r/111320*.7,dx=dy/Math.cos(l.y*Math.PI/180);const box=[l.x-dx,l.y-dy,l.x+dx,l.y+dy].join(',');$('aerial').src=`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=${box}&bboxSR=4326&imageSR=3857&size=1200,900&format=jpg&f=image`;}
async function fly(top=false){if(fallback){showAerial();return}if(!view||!Point)return;const l=current(),id=++moveId;$('status').textContent='Flying to your next mystery…';try{await view.goTo({target:new Point({longitude:l.x,latitude:l.y,z:l.z,spatialReference:{wkid:4326}}),scale:l.r*4,heading:0,tilt:top?0:55},{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:1800});if(id===moveId)$('status').textContent='';}catch(e){if(e.name!=='AbortError'&&id===moveId)$('status').textContent='Use Recenter to return to the landmark.'}}
window.initScene=()=>{if(typeof require!=='function'){mapFallback();return}require(['esri/Map','esri/views/SceneView','esri/layers/TileLayer','esri/layers/ElevationLayer','esri/geometry/Point'],(Map,SceneView,TileLayer,ElevationLayer,P)=>{Point=P;try{const map=new Map({basemap:{baseLayers:[new TileLayer({url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer'})]},ground:{layers:[new ElevationLayer({url:'https://elevation3d.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer'})]}});view=new SceneView({container:'scene',map,qualityProfile:'medium',ui:{components:['attribution','zoom','compass']},environment:{lighting:{date:new Date('2026-06-21T18:00:00Z'),directShadowsEnabled:false},atmosphereEnabled:true},popupEnabled:false});view.when(()=>{fallback=false;$('aerial').hidden=true;$('orbit').disabled=false;$('top').disabled=false;fly()},()=>mapFallback());}catch(e){mapFallback()}},()=>mapFallback())};
$('reset').onclick=()=>fly();$('top').onclick=()=>fly(true);$('orbit').onclick=()=>{if(view&&!fallback)view.goTo({heading:view.camera.heading+60},{duration:800}).catch(()=>{})};

function showPhoto(){const p=window.PHOTOS?.[queue[pos]];$('photoButton').hidden=!p?.src;if(!p?.src)return;$('photoButton').querySelector('span').textContent=p.title==='Poverty Point'?'Historical aerial photo · 1938 ⤢':'Reference photo ⤢';$('photoDialog').querySelector('h2').textContent=p.title==='Poverty Point'?'Historical aerial photo · 1938':'Take a closer look';$('landmarkPhoto').src=p.src;$('landmarkPhoto').onerror=()=>{$('photoButton').hidden=true};$('largePhoto').src=p.src;$('photoCredit').replaceChildren();const credit=document.createElement('span');credit.textContent=`Photo: ${p.author} · ${p.license} · `;const a=document.createElement('a');a.href=p.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Source & license ↗';$('photoCredit').append(credit,a);}
$('photoButton').onclick=()=>$('photoDialog').showModal();$('closePhoto').onclick=()=>$('photoDialog').close();

render();setTimeout(()=>{if((!view||!view.ready)&&!fallback)mapFallback()},20000);

