const LANDMARKS = [
  {
    "n": "Grand Canyon",
    "p": "Arizona, United States",
    "t": "Natural",
    "x": -112.11,
    "y": 36.1,
    "z": 2200,
    "r": 16000,
    "c": "A vast canyon exposes bands of rock, with the Colorado River far below.",
    "f": "The Colorado River carved this canyon into the Colorado Plateau. Its exposed rock layers preserve a long record of Earth’s history.",
    "s": "https://www.nps.gov/grca/learn/nature/geologicformations.htm"
  },
  {
    "n": "Grand Prismatic Spring",
    "p": "Yellowstone, Wyoming, United States",
    "t": "Natural",
    "x": -110.838,
    "y": 44.525,
    "z": 2230,
    "r": 800,
    "c": "A brilliant blue hot spring is surrounded by rings of yellow and orange.",
    "f": "This is Yellowstone’s largest hot spring. Heat-loving microorganisms contribute to the colorful bands around its edges.",
    "s": "https://www.usgs.gov/observatories/yvo/news/yellowstones-spectacular-spring-story-grand-prismatic-and-little-dipper"
  },
  {
    "n": "Bay of Fundy",
    "p": "New Brunswick–Nova Scotia, Canada",
    "t": "Natural",
    "x": -64.57333333,
    "y": 45.82333333,
    "z": 0,
    "r": 3500,
    "c": "Towering coastal rocks stand above exposed tidal flats. This Atlantic bay is famous for dramatic differences between high and low tide. The map focuses on its Hopewell Rocks shoreline.",
    "f": "The Bay of Fundy has an enormous tidal range. At Fundy National Park, high and low water can differ by as much as 12 metres. The bay’s natural rocking motion is reinforced by Atlantic tides. The reference photo shows Hopewell Rocks at low tide; the map imagery captures a fixed moment, not the current tide.",
    "s": "https://parks.canada.ca/pn-np/nb/fundy/nature/environment/marees-tides"
  },
  {
    "n": "Half Dome",
    "p": "Yosemite, California, United States",
    "t": "Natural",
    "x": -119.5332,
    "y": 37.7459,
    "z": 2690,
    "r": 6000,
    "c": "A granite summit has a rounded back and a striking, almost vertical face.",
    "f": "Half Dome is a granite landmark rising above Yosemite Valley. Its contrasting rounded profile and steep face are useful recognition clues.",
    "s": "https://www.nps.gov/yose/planyourvisit/halfdome.htm"
  },
  {
    "n": "Delicate Arch",
    "p": "Arches National Park, Utah, United States",
    "t": "Natural",
    "x": -109.4993,
    "y": 38.7436,
    "z": 1460,
    "r": 1000,
    "c": "A freestanding rock arch stands on two legs above a red-rock landscape.",
    "f": "Delicate Arch is a freestanding natural arch in Arches National Park. Look for the open space framed by the rock and its isolated position.",
    "s": "https://www.nps.gov/arch/planyourvisit/delicate-arch.htm"
  },
  {
    "n": "Devils Tower",
    "p": "Wyoming, United States",
    "t": "Natural",
    "x": -104.7153,
    "y": 44.5902,
    "z": 1558,
    "r": 3000,
    "c": "An isolated rock tower has a broad top and long vertical columns down its sides.",
    "f": "Devils Tower has distinctive columnar joints. Weathering breaks rock apart; erosion moves the broken material away.",
    "s": "https://www.nps.gov/deto/learn/nature/geologicformations.htm"
  },
  {
    "n": "Crater Lake",
    "p": "Oregon, United States",
    "t": "Natural",
    "x": -122.108,
    "y": 42.944,
    "z": 1883,
    "r": 15000,
    "c": "Deep blue water fills a volcanic basin surrounded by a high rim, with a small island inside.",
    "f": "Crater Lake formed after a volcanic eruption triggered a mountain’s collapse. Rain and snow feed this lake, the deepest in the United States.",
    "s": "https://www.nps.gov/crla/index.htm"
  },
  {
    "n": "Horseshoe Bend",
    "p": "Near Page, Arizona, United States",
    "t": "Natural",
    "x": -111.5104,
    "y": 36.8791,
    "z": 1050,
    "r": 3000,
    "c": "A river makes a tight U-shaped turn around a massive sandstone rock formation.",
    "f": "Horseshoe Bend is a deeply incised meander of the Colorado River near Page, Arizona. Its curved river channel is the key visual clue.",
    "s": "https://www.nps.gov/glca/planyourvisit/horseshoe-bend.htm"
  },
  {
    "n": "Monument Valley",
    "p": "Navajo Nation, Arizona–Utah, United States",
    "t": "Natural",
    "x": -110.098,
    "y": 36.982,
    "z": 1600,
    "r": 10000,
    "c": "Isolated sandstone buttes rise above a broad desert floor. Some resemble enormous mittens.",
    "f": "Monument Valley is within the Navajo Nation. Erosion helped shape its sandstone buttes, mesas, and spires.",
    "s": "https://navajonationparks.org/tribal-parks/monument-valley/"
  },
  {
    "n": "Bryce Canyon",
    "p": "Utah, United States",
    "t": "Natural",
    "x": -112.167,
    "y": 37.622,
    "z": 2450,
    "r": 6500,
    "c": "Dense clusters of thin rock spires fill a colorful natural amphitheater.",
    "f": "The rock spires are called hoodoos. Freezing water and other weathering processes help shape Bryce Canyon’s distinctive landscape.",
    "s": "https://www.nps.gov/brca/learn/nature/hoodoos.htm"
  },
  {
    "n": "Niagara Falls",
    "p": "Ontario, Canada / New York, United States",
    "t": "Natural",
    "x": -79.074,
    "y": 43.079,
    "z": 160,
    "r": 4200,
    "c": "A broad, curved waterfall and neighboring falls interrupt a river along an international border.",
    "f": "Niagara Falls includes Horseshoe Falls, American Falls, and Bridal Veil Falls. The Niagara River connects Lake Erie with Lake Ontario.",
    "s": "https://www.niagaraparks.com/visit-niagara-parks/plan-your-visit/niagara-falls-geology-facts-figures/"
  },
  {
    "n": "Lake Louise",
    "p": "Banff National Park, Alberta, Canada",
    "t": "Natural",
    "x": -116.219,
    "y": 51.416,
    "z": 1750,
    "r": 6500,
    "c": "A turquoise lake sits beneath high Rocky Mountain peaks, with a large hotel at one end.",
    "f": "Lake Louise is in Banff National Park in the Canadian Rockies. Its turquoise water and mountain setting are strong recognition clues.",
    "s": "https://parks.canada.ca/pn-np/ab/banff/visit/les10-top10/louise"
  },
  {
    "n": "Blythe Intaglios",
    "p": "California, United States",
    "t": "Human-made",
    "x": -114.53833333,
    "y": 33.80027778,
    "z": 160,
    "r": 500,
    "c": "Giant human and animal shapes are outlined on the desert floor. Their pale surfaces contrast with the darker gravel around them.",
    "f": "The Blythe Intaglios are large ground figures, or geoglyphs, near Blythe, California. The group contains six distinct figures in three locations, including human and animal forms. Their shapes are best appreciated from above.",
    "s": "https://www.blm.gov/visit/blythe-intaglios"
  },
  {
    "n": "Poverty Point Earthworks",
    "p": "Louisiana, United States",
    "t": "Human-made",
    "x": -91.4064,
    "y": 32.6369,
    "z": 30,
    "r": 2600,
    "c": "Six curved earthen ridges form nested arcs around a broad plaza, with large mounds nearby. Look for the geometric pattern in the landscape.",
    "f": "Indigenous hunter-fisher-gatherers built Poverty Point’s monumental earthworks in present-day Louisiana. Its six semi-elliptical ridges, central plaza, and large mounds formed a complex used for residential and ceremonial purposes.",
    "s": "https://whc.unesco.org/en/list/1435/"
  },
  {
    "n": "Hoover Dam",
    "p": "Nevada–Arizona border, United States",
    "t": "Human-made",
    "x": -114.7377,
    "y": 36.0156,
    "z": 220,
    "r": 3200,
    "c": "A massive curved concrete wall spans a narrow canyon, holding back a reservoir.",
    "f": "Hoover Dam is a concrete arch-gravity dam in Black Canyon on the Colorado River, at the Arizona–Nevada boundary.",
    "s": "https://www.usbr.gov/lc/hooverdam/faqs/damfaqs.html"
  },
  {
    "n": "Chichén Itzá",
    "w": "Chichen Itza",
    "p": "Yucatán, Mexico",
    "t": "Human-made",
    "x": -88.5686,
    "y": 20.6843,
    "z": 25,
    "r": 1500,
    "c": "A stepped pyramid with stairways on its four sides dominates an ancient city on the Yucatán Peninsula.",
    "f": "Chichén Itzá was a major Maya center. The stepped pyramid known as El Castillo is one of its most recognizable monuments.",
    "s": "https://whc.unesco.org/en/list/483/"
  },
  {
    "n": "Teotihuacán",
    "w": "Teotihuacan",
    "p": "Near Mexico City, Mexico",
    "t": "Human-made",
    "x": -98.8438,
    "y": 19.6925,
    "z": 2280,
    "r": 4500,
    "c": "Large pyramids stand beside a long, straight ceremonial avenue near Mexico City.",
    "f": "Teotihuacán is known for the Avenue of the Dead and the Pyramids of the Sun and Moon. These large structures define its urban layout.",
    "s": "https://whc.unesco.org/en/list/414/"
  },
  {
    "n": "Tikal",
    "p": "Petén, Guatemala",
    "t": "Human-made",
    "x": -89.6237,
    "y": 17.222,
    "z": 280,
    "r": 2600,
    "c": "Tall, steep-sided temple pyramids rise above a tropical forest canopy.",
    "f": "Tikal was a major Maya city in what is now northern Guatemala. Its temples and plazas stand within tropical forest.",
    "s": "https://whc.unesco.org/en/list/64/"
  },
  {
    "n": "Panama Canal",
    "p": "Panama · Miraflores Locks",
    "t": "Human-made",
    "x": -79.5918,
    "y": 8.9963,
    "z": 15,
    "r": 4500,
    "c": "Parallel lock chambers lift and lower ships along a shortcut between two oceans.",
    "f": "The Panama Canal connects the Atlantic and Pacific oceans. Its locks raise and lower ships between bodies of water at different elevations.",
    "s": "https://pancanal.com/en/"
  },
  {
    "n": "Great Blue Hole",
    "p": "Lighthouse Reef, Belize",
    "t": "Natural",
    "x": -87.5349,
    "y": 17.3156,
    "z": 0,
    "r": 1600,
    "c": "An almost circular, dark-blue hole contrasts with shallow turquoise water inside a coral reef.",
    "f": "The Great Blue Hole is a marine sinkhole at Lighthouse Reef off Belize. Its circular outline and color contrast make it recognizable from above.",
    "s": "https://www.travelbelize.org/attraction/blue-hole/"
  },
  {
    "n": "Arenal Volcano",
    "p": "Costa Rica",
    "t": "Natural",
    "x": -84.7032,
    "y": 10.4634,
    "z": 1670,
    "r": 8500,
    "c": "A steep, cone-shaped volcano rises above a green landscape beside a large lake.",
    "f": "Arenal is a volcano in northern Costa Rica. Its prominent cone rises above the eastern shore of Lake Arenal.",
    "s": "https://volcano.si.edu/volcano.cfm?vn=345033"
  },
  {
    "n": "The Pitons",
    "w": "Pitons",
    "p": "Saint Lucia, Caribbean",
    "t": "Natural",
    "x": -61.066,
    "y": 13.815,
    "z": 400,
    "r": 6500,
    "c": "Two steep volcanic peaks rise close together beside the Caribbean Sea.",
    "f": "Gros Piton and Petit Piton are volcanic spires on Saint Lucia. They are the defining features of the Pitons Management Area.",
    "s": "https://whc.unesco.org/en/list/1161/"
  },
  {
    "n": "Cahokia Mounds",
    "p": "Illinois, United States · Monks Mound",
    "t": "Human-made",
    "x": -90.0621,
    "y": 38.66,
    "z": 155,
    "r": 2200,
    "c": "Broad, grassy earthen mounds rise above a flat landscape. A massive terraced mound dominates this ancient settlement.",
    "f": "Cahokia was a major center of Mississippian culture in present-day Illinois. Its inhabitants built earthen mounds, including Monks Mound, which rises in four terraces. These are human-built earthworks, not natural hills.",
    "s": "https://whc.unesco.org/en/list/198/"
  },
  {
    "n": "Mesa Verde Cliff Dwellings",
    "p": "Colorado, United States · Cliff Palace",
    "t": "Human-made",
    "x": -108.4733,
    "y": 37.1678,
    "z": 2070,
    "r": 1300,
    "c": "Stone rooms and towers fit beneath an overhanging sandstone cliff. Circular chambers lie among the buildings.",
    "f": "Ancestral Pueblo people built Mesa Verde’s cliff dwellings using sandstone, mortar, and wooden beams. The view here centers on Cliff Palace, a large dwelling with 150 rooms and 23 kivas.",
    "s": "https://www.nps.gov/meve/learn/historyculture/cliff_palace.htm"
  },
  {
    "n": "Great Serpent Mound",
    "p": "Ohio, United States",
    "t": "Human-made",
    "x": -83.43083333,
    "y": 39.02638889,
    "z": 240,
    "r": 1000,
    "c": "A long, winding earthen mound traces the shape of a snake, ending in a tightly curled tail. Look for its curves across the grassy landscape.",
    "f": "Great Serpent Mound is an Indigenous earthwork in Ohio. It is an effigy mound: a mound built in the shape of an animal. Its snake form and curled tail distinguish it from the platform mounds and geometric ridges at other earthwork sites.",
    "s": "https://www.ohiohistory.org/visit/browse-historical-sites/serpent-mound/"
  }
];

